name: Deploy Documentation

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Docusaurus CLIs are Node-based; keep Node available
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: bun install --frozen-lockfile

      # Generate TypeDoc API documentation (reads from source files)
      - name: Generate API docs
        run: bun run docs:api

      # Build docs site (will use pre-generated API docs)
      - name: Build docs site
        run: bun run docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: apps/docs/build
          publish_branch: docs
          cname: false
