name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.23

      - name: Setup Node & npm registry
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Build all packages
        run: bun run build

      - name: Check for changesets
        id: check-changesets
        run: |
          if [ -n "$(ls -A .changeset/*.md 2>/dev/null | grep -v 'README.md\|config.json')" ]; then
            echo "has-changesets=true" >> $GITHUB_OUTPUT
          else
            echo "has-changesets=false" >> $GITHUB_OUTPUT
            echo "No changesets found. Skipping release."
          fi

      # Changesets will open/update PRs for versioning and changelogs,
      # and after merge, it will publish to npm.
      - name: Changesets
        if: steps.check-changesets.outputs.has-changesets == 'true'
        uses: changesets/action@v1
        with:
          publish: bun run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
